[Var]
No = 1
Name = Test
Value = 5

;=============================

[Var]
No = 2
Name = 战场物件 放大系数 (abort)
Value = 1.0

;=============================

[Var]
No = 3
Name = 战场镜头 Z
Value = 230

[Var]
No = 4
Name = 战场镜头锁定物件时 Y 位差 
Value = 50

;=============================

[Var]
No = 5
Name = 战场格的 x 
Value = 100

[Var]
No = 6
Name = 战场格的 y
Value = 60

;=============================

[Var]
No = 7
Name = 战场背景 Y 位差 
Value = 30

;=============================

[Var]
No = 8
Name = 战场 Camera 移动范围 x min offset
Value = 0

[Var]
No = 9
Name = 战场 Camera 移动范围 x max offset
Value = 0

[Var]
No = 10
Name = 战场 Camera 移动范围 y min offset
Value = 70

[Var]
No = 11
Name = 战场 Camera 移动范围 y max offset
Value = 100

[Var]
No = 12
Name = 战场 Camera 移动范围 z min
Value = 150

[Var]
No = 13
Name = 战场 Camera 移动范围 z max
Value = 1200

[Var]
No = 14
Name = 战场 Camera 移动 x , y, z 的 位移量
Value = 30 , 15, 3

;=============================